#!/usr/bin/env bash
# Launches the client with Ultima's opt-in frame-time recorder.
#
# Usage: bash scripts/bench-client.sh <run-label> <disabled|default|enabled>
#
# Primary release A/B is disabled versus default. Do not use enabled as the ON side of a
# release comparison; that mode force-enables experimental opt-in modules.
#
# Both sides receive identical JVM flags, program args, camera path, resolution, and recorder
# overhead. Only ultima.properties module states differ (client_benchmark stays on for both).
#
# Environment:
#   GAME_DIR           Optional Minecraft game directory (Windows paths are converted)
#   WORLD              Optional save folder for --quickPlaySingleplayer
#   WIDTH/HEIGHT       Window size (default 1280x720)
#   WARMUP_FRAMES      Default 1200
#   SAMPLE_FRAMES      Default 12000
#   CAMERA_MODE        stationary (default), yaw_sweep, or chunk_flight
#   CAMERA_X/Y/Z       Optional held/start position
#   CAMERA_YAW/PITCH   Optional look angles
#   CAMERA_YAW_PER_FRAME  Degrees per frame for yaw_sweep/chunk_flight (default 0.25)
#   CAMERA_Z_PER_FRAME    Blocks per frame for chunk_flight (default 0.8)
#   SCENE              Label recorded in JSON
#   PAIR_LABEL         Label recorded in JSON
#   CAPTURE_SCREENSHOTS  Set to 1 to grab sample_start/sample_end screenshots
#   EXIT_AFTER_WRITE   Default 1; close the client only after JSON is written
set -euo pipefail

LABEL="${1:?usage: bench-client.sh <run-label> <disabled|default|enabled>}"
MODE="${2:?usage: bench-client.sh <run-label> <disabled|default|enabled>}"
WARMUP_FRAMES="${WARMUP_FRAMES:-1200}"
SAMPLE_FRAMES="${SAMPLE_FRAMES:-12000}"
WIDTH="${WIDTH:-1280}"
HEIGHT="${HEIGHT:-720}"
CAMERA_MODE="${CAMERA_MODE:-stationary}"
SCENE="${SCENE:-stationary_overworld}"
PAIR_LABEL="${PAIR_LABEL:-$LABEL}"
EXIT_AFTER_WRITE="${EXIT_AFTER_WRITE:-1}"
CAPTURE_SCREENSHOTS="${CAPTURE_SCREENSHOTS:-0}"

if [[ ! "$MODE" =~ ^(disabled|default|enabled)$ ]]; then
  echo "mode must be exactly 'disabled', 'default', or 'enabled'" >&2
  exit 2
fi
if [[ ! "$LABEL" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo "label may contain only letters, digits, dot, underscore, and hyphen" >&2
  exit 2
fi
if [[ "$MODE" == enabled ]]; then
  echo "WARNING: mode=enabled force-enables experimental opt-in modules." >&2
  echo "WARNING: it is not the primary release A/B. Use disabled vs default." >&2
  if [[ "${ALLOW_EXPERIMENTAL_ON:-}" != 1 ]]; then
    echo "Refusing enabled without ALLOW_EXPERIMENTAL_ON=1." >&2
    exit 2
  fi
fi

cd "$(dirname "$0")/.."
bash scripts/ensure-wrapper.sh
mkdir -p run

to_java_path() {
  local input="$1"
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -m -- "$input"
    return
  fi
  case "$input" in
    /[a-zA-Z]/*)
      local drive
      drive="$(printf '%s' "$input" | cut -c2 | tr '[:lower:]' '[:upper:]')"
      printf '%s:/%s\n' "$drive" "$(printf '%s' "$input" | cut -c4-)"
      ;;
    *)
      printf '%s\n' "${input//\\//}"
      ;;
  esac
}

GAME_DIR_JAVA=""
if [[ -n "${GAME_DIR:-}" ]]; then
  GAME_DIR_JAVA="$(to_java_path "$GAME_DIR")"
fi

CONFIG_ROOT="${GAME_DIR_JAVA:-$PWD/run}"
mkdir -p "${CONFIG_ROOT}/config"

mapfile -t MODULE_ENTRIES < <(
  awk '/(new Module|Module\.client)\("[a-z_]+", (true|false),/ {
    line = $0
    state = line
    sub(/^.*(new Module|Module\.client)\("/, "", line)
    sub(/".*$/, "", line)
    sub(/^.*", /, "", state)
    sub(/,.*/, "", state)
    print line "=" state
  }' src/main/java/dev/ultima/config/UltimaModules.java
)
if (( ${#MODULE_ENTRIES[@]} == 0 )); then
  echo "failed to discover optimization module keys" >&2
  exit 1
fi

{
  echo "# Generated by scripts/bench-client.sh for label=${LABEL} mode=${MODE}"
  echo "# Primary release A/B is disabled versus default."
  for entry in "${MODULE_ENTRIES[@]}"; do
    key="${entry%%=*}"
    default_state="${entry#*=}"
    if [[ "$key" == client_benchmark ]]; then
      state=true
    else
      case "$MODE" in
        enabled) state=true ;;
        disabled) state=false ;;
        default) state="$default_state" ;;
      esac
    fi
    printf '%s=%s\n' "$key" "$state"
  done
} > "${CONFIG_ROOT}/config/ultima.properties"

OUTPUT_UNIX="$PWD/run/ultima-client-benchmark-${LABEL}.json"
OUTPUT_JAVA="$(to_java_path "$OUTPUT_UNIX")"
SCREENSHOT_PREFIX="ultima-client-benchmark-${LABEL}"

write_jvm_prop() {
  printf '%s=%s\n' "$1" "$2"
}

{
  write_jvm_prop "ultima.clientBenchmark" "true"
  write_jvm_prop "ultima.clientBenchmark.warmupFrames" "$WARMUP_FRAMES"
  write_jvm_prop "ultima.clientBenchmark.sampleFrames" "$SAMPLE_FRAMES"
  write_jvm_prop "ultima.clientBenchmark.output" "$OUTPUT_JAVA"
  write_jvm_prop "ultima.clientBenchmark.exitAfterWrite" "$([[ "$EXIT_AFTER_WRITE" == 1 ]] && echo true || echo false)"
  write_jvm_prop "ultima.clientBenchmark.captureScreenshots" "$([[ "$CAPTURE_SCREENSHOTS" == 1 ]] && echo true || echo false)"
  write_jvm_prop "ultima.clientBenchmark.screenshotPrefix" "$SCREENSHOT_PREFIX"
  write_jvm_prop "ultima.clientBenchmark.cameraMode" "$CAMERA_MODE"
  write_jvm_prop "ultima.clientBenchmark.scene" "$SCENE"
  write_jvm_prop "ultima.clientBenchmark.pairLabel" "$PAIR_LABEL"
  write_jvm_prop "ultima.clientBenchmark.abRole" "$MODE"
  if [[ -n "${WORLD:-}" ]]; then
    write_jvm_prop "ultima.clientBenchmark.worldId" "$WORLD"
  fi
  if [[ -n "${CAMERA_X:-}" ]]; then write_jvm_prop "ultima.clientBenchmark.cameraX" "$CAMERA_X"; fi
  if [[ -n "${CAMERA_Y:-}" ]]; then write_jvm_prop "ultima.clientBenchmark.cameraY" "$CAMERA_Y"; fi
  if [[ -n "${CAMERA_Z:-}" ]]; then write_jvm_prop "ultima.clientBenchmark.cameraZ" "$CAMERA_Z"; fi
  if [[ -n "${CAMERA_YAW:-}" ]]; then write_jvm_prop "ultima.clientBenchmark.cameraYaw" "$CAMERA_YAW"; fi
  if [[ -n "${CAMERA_PITCH:-}" ]]; then write_jvm_prop "ultima.clientBenchmark.cameraPitch" "$CAMERA_PITCH"; fi
  if [[ -n "${CAMERA_YAW_PER_FRAME:-}" ]]; then
    write_jvm_prop "ultima.clientBenchmark.cameraYawDegreesPerFrame" "$CAMERA_YAW_PER_FRAME"
  fi
  if [[ -n "${CAMERA_Z_PER_FRAME:-}" ]]; then
    write_jvm_prop "ultima.clientBenchmark.cameraZPerFrame" "$CAMERA_Z_PER_FRAME"
  fi
  if [[ -n "${HOLD_POSITION:-}" ]]; then
    write_jvm_prop "ultima.clientBenchmark.holdPosition" "$([[ "$HOLD_POSITION" == 1 ]] && echo true || echo false)"
  fi
} > run/bench-client.jvm.properties

{
  echo "--width"
  echo "$WIDTH"
  echo "--height"
  echo "$HEIGHT"
  if [[ -n "${WORLD:-}" ]]; then
    echo "--quickPlaySingleplayer"
    echo "$WORLD"
  elif [[ "${QUICKPLAY:-}" == 1 ]]; then
    echo "--quickPlaySingleplayer"
  fi
  if [[ -n "$GAME_DIR_JAVA" ]]; then
    echo "--gameDir"
    echo "$GAME_DIR_JAVA"
  fi
} > run/bench-client.program.args

GRADLE_ARGS=(--no-daemon runClient -Pultima.bench=1)
if [[ -n "$GAME_DIR_JAVA" ]]; then
  GRADLE_ARGS+=("-Pultima.gameDir=${GAME_DIR_JAVA}")
fi

echo "Client benchmark mode: ${MODE}"
echo "Label: ${LABEL}"
echo "Output: ${OUTPUT_JAVA}"
echo "Config: ${CONFIG_ROOT}/config/ultima.properties"
echo "Camera: ${CAMERA_MODE}"
echo "Scene: ${SCENE}"
echo "Resolution: ${WIDTH}x${HEIGHT}"
echo "Recorder: warmup=${WARMUP_FRAMES} sample=${SAMPLE_FRAMES} exitAfterWrite=${EXIT_AFTER_WRITE}"
echo "Keep world copy, camera path, resolution, distances, graphics, shaders, packs, and population identical."
echo "Primary release comparison is disabled versus default, not enabled."
echo "== module states (${MODE}) =="
cat "${CONFIG_ROOT}/config/ultima.properties"

./gradlew "${GRADLE_ARGS[@]}"

if [[ -f "$OUTPUT_UNIX" ]]; then
  echo "Wrote ${OUTPUT_UNIX}"
elif [[ -f "$OUTPUT_JAVA" ]]; then
  echo "Wrote ${OUTPUT_JAVA}"
else
  echo "benchmark JSON was not written: ${OUTPUT_UNIX}" >&2
  exit 1
fi
